// activityIdeas.js
// 100 idee per attività ludiche e sociali (17-25 anni)

const activityIdeas = [
    // 🍔 Cibo & Bevande (Food & Social)
    "Andiamo a mangiare sushi 'All You Can Eat'?",
    "Serata pizza e birra artigianale.",
    "Aperitivo o apericena in centro.",
    "Proviamo quel nuovo locale etnico (thai, messicano, indiano)?",
    "Serata hamburger gourmet.",
    "Organizziamo un brunch nel weekend.",
    "Picnic al parco (appena c'è sole).",
    "Organizziamo un barbecue in giardino.",
    "Gara di cucina a casa: chi fa il piatto migliore?",
    "Prendiamo un bubble tea e facciamo due passi.",
    "Giro di street food in centro.",
    "Serata cocktail bar, proviamo drink nuovi.",
    "Gelato artigianale dopo cena.",
    "Poke bowl per un pranzo veloce e sano.",
    "Kebab notturno (un classico).",
    "Proviamo una vineria o un'enoteca.",
    "Serata crêpes (dolci e salate) fatte in casa.",
    "Andiamo a una sagra di paese.",
    "Caffè e chiacchiere in quel nuovo bar.",
    "Cuciniamo qualcosa di complicato tutti insieme.",

    // 🎬 Intrattenimento & Cultura
    "Cinema: c'è quel nuovo film da vedere.",
    "Concerto di musica live in un locale.",
    "Andiamo a ballare in discoteca?",
    "Spettacolo di stand-up comedy.",
    "Visitiamo una mostra d'arte moderna o di fotografia.",
    "Andiamo a una fiera (fumetti, videogiochi, dischi).",
    "Teatro? Magari qualcosa di comico.",
    "Gita di un giorno in una città vicina (in treno).",
    "Cinema all'aperto (d'estate).",
    "Serata karaoke (anche se siamo stonati).",
    "Visita a un museo (magari scientifico o interattivo).",
    "Pub quiz: formiamo una squadra e vinciamo?",
    "Mercatino vintage o dell'usato.",
    "Proviamo la 'Silent Disco'.",
    "Esploriamo un quartiere della città che non conosciamo.",

    // 🏆 Giochi & Attività di Gruppo
    "Partita a bowling: chi fa strike?",
    "Laser tag a squadre.",
    "Gara sui go-kart.",
    "Escape Room: riusciamo a uscire in tempo?",
    "Partita a calcetto.",
    "Proviamo a giocare a Padel.",
    "Pomeriggio in sala giochi (arcade).",
    "Torneo di FIFA o Mario Kart a casa.",
    "Serata giochi da tavolo (Risiko, Catan, Cluedo).",
    "Paintball nel weekend.",
    "Arrampicata indoor (bouldering).",
    "Minigolf.",
    "Sessione di Dungeons & Dragons (D&D).",
    "Proviamo una sala di Realtà Virtuale (VR).",
    "Biliardo e birra al pub.",
    "Freccette al pub.",
    "Serata 'Murder Party' (cena con delitto).",
    "Geocaching: caccia al tesoro con il GPS.",
    "Proviamo il 'lancio dell'ascia' (axe throwing).",
    "Organizziamo una caccia al tesoro personalizzata.",

    // 🌳 Sport & Aria Aperta
    "Semplice passeggiata in centro.",
    "Passeggiata al parco o sul lungomare.",
    "Giro in bici o in monopattino elettrico.",
    "Trekking in collina o montagna.",
    "Giornata al lago (con pedalò o kayak).",
    "Giornata in spiaggia (anche solo per passeggiare).",
    "Pattinare (sul ghiaccio d'inverno, rollerblade d'estate).",
    "Andiamo in skatepark.",
    "Giornata in piscina o in un parco acquatico.",
    "Guardare il tramonto da un punto panoramico.",
    "Giro in macchina di notte ascoltando musica.",
    "Andare a vedere le stelle (lontano dalle luci).",
    "Giornata in un parco divertimenti.",
    "Andare a vedere una partita (calcio, basket, volley).",
    "Fare un falò (dove consentito).",
    "Partita a beach volley.",
    "Yoga o allenamento di gruppo al parco.",
    "Giornata alle terme o spa.",
    "Noleggiamo le city bike.",
    "Proviamo uno sport d'acqua (tipo SUP).",

    // 🏠 Relax, Creatività & Low Cost
    "Maratona di una serie TV (Netflix/Prime) con pizza.",
    "Costruire un set LEGO complicato.",
    "Pomeriggio studio in biblioteca (con molte pause).",
    "Shooting fotografico urbano.",
    "Imparare a fare cocktail a casa.",
    "Serata 'Jackbox Games' (usando i telefoni).",
    "Fare volontariato per un giorno (es. canile).",
    "Andiamo in una grande libreria a curiosare.",
    "Visita a un giardino botanico.",
    "Organizziamo uno 'swap party' (scambio vestiti).",
    "Corso di cucina di un giorno (es. sushi, pasta).",
    "Corso di ceramica o pittura (Paint and Sip).",
    "Riunirsi per suonare (jam session).",
    "Andare a un evento 'open mic'.",
    "Semplicemente: trovarsi su una panchina e parlare."
];

// Esempio di come usarlo (opzionale):
// const ideaCasuale = activityIdeas[Math.floor(Math.random() * activityIdeas.length)];
// console.log("Cosa facciamo stasera?");
// console.log(ideaCasuale);
