// frasi.js
const decisionPhrases = [
    // Frasi affermative
    "È assolutamente certo.",
    "Senza dubbio.",
    "Assolutamente sì.",
    "Puoi contare su di questo.",
    "Come lo vedo io, sì.",
    "Molto probabile.",
    "La prospettiva è buona.",
    "Sì.",
    "I segni indicano sì.",
    "È sicuro.",
    "Dovresti scommetterci.",
    "Le stelle sono allineate.",
    "Sì, ma con cautela.",
    "È il momento giusto.",
    "Vai avanti!",
    // Frasi non committenti
    "Risposta confusa, riprova.",
    "Chiedi più tardi.",
    "Meglio non dirtelo ora.",
    "Non posso prevederlo ora.",
    "Concentrati e chiedi di nuovo.",
    "Devi aspettare.",
    "Troppo presto per dirlo.",
    "Non è la priorità.",
    "Lascia perdere per ora.",
    "I dati non sono sufficienti.",
    "Dipende da te.",
    "Non affrettare i tempi.",
    "Forse, forse no.",
    "La nebbia è fitta.",
    "Non sono un esperto.",
    // Frasi negative
    "Non ci contare.",
    "La mia risposta è no.",
    "Le mie fonti dicono di no.",
    "Molto improbabile.",
    "Non va bene.",
    "No.",
    "Assolutamente no.",
    "È un rischio troppo grande.",
    "C'è un blocco stradale.",
    "Riconsidera la cosa.",
    "È fuori questione.",
    "Non è la scelta giusta.",
    "Sarebbe un errore.",
    "Non ora.",
    "Lascia perdere.",
    // Frasi aggiuntive per raggiungere 50+
    "La risposta è nascosta.",
    "Sì, ma lentamente.",
    "Cerca un'alternativa.",
    "Segui il tuo istinto.",
    "Fallo e basta.",
    "Non c'è fretta.",
    "Chiedi a un amico.",
    "Tutto è possibile.",
    "Non te ne pentirai.",
    "Non è garantito.",
    "Prova qualcosa di nuovo.",
    "Il destino ha deciso.",
    "Stai attento!",
    "La palla è nelle tue mani."
];
